apiVersion: v1
kind: Service
metadata:
  name: {{ include "nitrohook.fullname" . }}-redis
  labels:
    {{- include "nitrohook.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  clusterIP: None
  selector:
    {{- include "nitrohook.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
